CpaRepository/Controllers/Admin/CpaModulesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Interfaces.EF;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Web.Controllers.Admin
{
    public class CpaModulesController : Controller
    {
        private readonly ILogger<CpaModulesController> _logger;
        private IRepository<CpaModule> _repo;
        public CpaModulesController(IRepository<CpaModule> repo, ILogger<CpaModulesController> logger)
        {
            _repo = repo ?? throw new ArgumentNullException(nameof(repo));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
        public ActionResult CpaModule()
        {
            try
            {
                IEnumerable<CpaModule> module = _repo.GetAll();
                return View(module);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Index), "HomeController");
            }
        }

        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<ActionResult> Create(CpaModule module)
        {
           
            try
            {
                await _repo.AddAsync(module);
                return RedirectToAction(nameof(CpaModule));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            try
            {
                var module = _repo.GetById(id);
                return View(module);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(CpaModule));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CpaModule module)
        {
            try
            {
                await _repo.UpdateAsync(module);
                return RedirectToAction(nameof(CpaModule));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
        
        public ActionResult Delete(int id)
        {
            try
            {
                var vendor = _repo.GetById(id);
                return View(vendor);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(CpaModule));
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var module = _repo.GetById(id);
                await _repo.DeleteAsync(module);
                return RedirectToAction(nameof(CpaModule));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
    }
}

CpaRepository/Controllers/Admin/LettersController.cs
using AutoMapper;
using Core.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Mediatr.Command.LetterController;
using Web.Mediatr.Query.LetterController;
using Web.ViewModel.Letter;

namespace Web.Controllers.Admin
{
    public class LettersController : Controller
    {
        private readonly ILogger<LettersController> _logger;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        public LettersController(IMapper mapper, IMediator mediator, ILogger<LettersController> logger)
        {
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));      
        }
        public async Task< ActionResult> Letters()
        {
            try
            {             
                var letters = await _mediator.Send(new GetAllLettersQuery());
                var vm = _mapper.Map<IEnumerable<LetterViewModel>>(letters).OrderByDescending(n => n.DateOfLetter);
              
                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Index), "HomeController");
            }
        }
        
        public async Task<ActionResult> Create()
        {
            try
            {
                var vm = await _mediator.Send(new GetVmForLetterCreateQuery());            
                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Letters));
            }
        }
       
        [HttpPost]
        public async Task<ActionResult> Create(LetterViewModel vm)
        {
            try
            {
                if (vm.FileLetter != null)
                {        
                    var letter = await _mediator.Send(new CreateLetterCommand()
                    {
                        Letter = _mapper.Map<Letter>(vm),
                        FileLetter = vm.FileLetter
                    });
                    if (letter != null)
                    {
                        _logger.LogInformation($"Добавлен согласованный модуль. " +
                           $"Вендор - {letter.Vendor.Name}, " +
                           $"Номер - {letter.NumberLetter}, " +
                           $"Время - {DateTime.Now}");
                        return RedirectToAction(nameof(Letters));
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    _logger.LogError("Отсуствует файл.");
                    return View();
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
        
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var vm = await _mediator.Send(new GetVmForLetterEditQuery() { Id = id });                

                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Letters));
            }
        }
        
        [HttpPost]
        public async Task<ActionResult> Edit(LetterViewModel vm)
        {
            try
            {
                var res = await _mediator.Send(new EditLetterCommand()
                {
                    Letter = _mapper.Map<Letter>(vm),
                    FileLetter = vm.FileLetter
                });

                return RedirectToAction(nameof(Letters));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(vm.Id);
            }          
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var letter = await _mediator.Send(new GetLetterByIdLetterQuery() { Id = id });              
                return View(letter);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Letters));
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _mediator.Send(new DeleteLetterCommand() { Id = id });                           
                return RedirectToAction(nameof(Letters));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
       
        public async Task<IActionResult> DownloadFile(int id)
        {
            try
            {              
                var file = await _mediator.Send(new GetFileLetterQuery() { Id = id });
                if (file != null)
                {
                    return file;
                }
                else
                {
                    _logger.LogError("Отсутствует файл письма.");
                    return RedirectToAction(nameof(Letters));
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Letters));
            }
        }
    }
}

CpaRepository/Controllers/Admin/VendorModuleController.cs
using AutoMapper;
using Core.Models;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;
using Web.Mediatr.Command.VendorModuleController;
using Web.Mediatr.Query.VendorModuleController;
using Web.ViewModel.VendorModule;

namespace Web.Controllers.Admin
{
    public class VendorModuleController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;
        private readonly ILogger<VendorModuleController> _logger;
        public VendorModuleController(IMapper mapper, IMediator mediator, ILogger<VendorModuleController> logger)
        {
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _mediator = mediator ?? throw new ArgumentNullException(nameof(mediator));         
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<ActionResult> VendorModule(int id)
        {
            try
            {
                var vm = await _mediator.Send(new GetVendorModuleQuery() { Id = id });
                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Index), "HomeController");
            }
        }

        public async Task<ActionResult> Create(int id)
        {
            try
            {
                var vm = await _mediator.Send(new GetVmForVendorModuleCreateQuery() { Id = id });
                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(VendorModule), new { id = id });
            }
        }

        [HttpPost]
        public async Task<ActionResult> Create(VendorModuleViewModel vm)
        {
            try
            {
                vm.Id = 0;
                var vendorModule = await _mediator.Send(new CreateVendorModuleCommand()
                {
                    VendorModule = _mapper.Map<VendorModule>(vm)
                });

                return RedirectToAction(nameof(VendorModule), new { id = vm.VendorId });
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var vm = await _mediator.Send(new GetVmForVendorModuleEditQuery() { Id = id });

                return View(vm);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(VendorModule), new { id = 1 });
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(VendorModuleViewModel vm)
        {
            try
            {
                var vendorModule = await _mediator.Send(new EditVendorModuleCommand()
                {
                    VendorModule = _mapper.Map<VendorModule>(vm)
                });
               
                return RedirectToAction(nameof(VendorModule), new { id = vm.VendorId });
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View(vm.Id);
            }
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var module = await _mediator.Send(new GetVendorModuleByIdQuery() { Id = id });
                return View(module);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(VendorModule), new { id = 1 });
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var res = await _mediator.Send(new DeleteVendorModuleCommand() { Id = id });
                return RedirectToAction(nameof(VendorModule), new { id = res.Item2 });
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
    }
}

CpaRepository/Controllers/Admin/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Core.Interfaces.EF;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Web.Controllers.Admin
{
    public class VendorsController : Controller
    {
        private readonly ILogger<VendorsController> _logger;
        private IRepository<Vendor> _repo;
        public VendorsController(IRepository<Vendor> repo, ILogger<VendorsController> logger)
        {
            _repo = repo ?? throw new ArgumentNullException(nameof(repo));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }
        public ActionResult Vendor()
        {
            try
            {
                IEnumerable<Vendor> vendors = _repo.GetAll();
                return View(vendors);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Index), "HomeController");
            }
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Vendor vendor)
        {
            try
            {
                await _repo.AddAsync(vendor);
                return RedirectToAction(nameof(Vendor));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                var model = _repo.GetById(id);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Vendor));
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Vendor vendor)
        {
            try
            {
                await _repo.UpdateAsync(vendor);
                return RedirectToAction(nameof(Vendor));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                var vendor = _repo.GetById(id);
                return View(vendor);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return RedirectToAction(nameof(Vendor));
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var module = _repo.GetById(id);
                await _repo.DeleteAsync(module);
                return RedirectToAction(nameof(Vendor));
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
                return View();
            }
        }
    }
}

CpaRepository/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CpaRepository</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/logo_ru.png">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Modules" asp-action="ActualModules">Актуальные модули</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Modules" asp-action="ArchiveModules">Архив модулей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Letters" asp-action="Letters">Загрузить письмо</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="AgreedModules" asp-action="AgreedModules">Загрузить модуль</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Настройки
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendors" asp-action="Vendor">Вендоры</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="CpaModules" asp-action="CpaModule">Модули ТПР</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="VendorModule" asp-action="VendorModule" asp-route-id="1">Модули Prosoft</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="VendorModule" asp-action="VendorModule" asp-route-id="2">Модули Emicon</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="VendorModule" asp-action="VendorModule" asp-route-id="3">Модули Siemens</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="VendorModule" asp-action="VendorModule" asp-route-id="4">Модули B&R</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="VendorModule" asp-action="VendorModule" asp-route-id="5">Модули SE</a>

                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CpaRepository - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- <script src="~/lib/jquery/dist/jquery.min.js"></script>
     <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="~/js/site.js" asp-append-version="true"></script>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

   

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>